---
name: test
on: pull_request
permissions: {}
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
jobs:
  # Please don't add jobs to this file. Add them to .github/workflows/workflow_call_test.yaml
  status-check:
    runs-on: ubuntu-24.04
    if: failure()
    timeout-minutes: 10
    permissions: {}
    needs:
      - test
    steps:
      - name: Some other jobs failed
        run: |
          echo "::error:: Some other jobs failed. Please check $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          exit 1
  test:
    uses: ./.github/workflows/workflow_call_test.yaml
    permissions:
      contents: read
  # Please don't add jobs to this file. Add them to .github/workflows/workflow_call_test.yaml
